export const assets = {
  discordbot: {
    name: "discordbot",
    model: "discordbot.glb",
    texture: "ChassisBake.png",
    mesh: [],
    url: "https://github.com/gustavo-tomas/DiscordBot",
    hover: false,
  },
  todorust: {
    name: "todorust",
    model: "todorust.glb",
    texture: "NoteBake.png",
    mesh: [],
    url: "https://github.com/gustavo-tomas/ToDoRust",
    hover: false,
  },
  balancasolucoes: {
    name: "balancasolucoes",
    model: "balancasolucoes.glb",
    texture: "BalancaBake.png",
    mesh: [],
    url: "https://github.com/gustavo-tomas/BalancaSolucoes",
    hover: false,
  },
  github: {
    name: "github",
    model: "github.glb",
    texture: "GithubBake.png",
    mesh: [],
    url: "https://github.com/gustavo-tomas",
    hover: false,
  },
  // test: {
  //   name: "test",
  //   model: "test.glb",
  //   texture: "TestBake.png",
  //   mesh: [],
  //   hover: false,
  // },
};